import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from 'geist/font/sans';


export const metadata: Metadata = {
  title: "Next To-Do",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>{children}</body>
    </html>
  );
}
